#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
  path: /
  controller: App\Controller\LoginController::login

app_register:
  path: /register
  controller: App\Controller\RegisterController::register

app_events:
  path: /events
  controller: App\Controller\EventsController::events
