#index:
#    path: /
#    controller: App\Controller\SecurityController::login

#app_login:
#  path: /
#  controller: App\Controller\LoginController::login

#app_register:
#  path: /register
#  controller: App\Controller\RegisterController::register

app_events:
  path: /events
  controller: App\Controller\EventsController::events

app_order:
  path: /order
  controller: App\Controller\OrderController::order

app_add-event:
  path: /addEvent
  controller: App\Controller\EventsController::addEvent

app_login:
  path: /
  controller: App\Controller\SecurityController::login

app_register_symfony:
  path: /register
  controller: App\Controller\RegistrationController::register