easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Users
        - App\Entity\Events
        - App\Entity\Orders
        - App\Entity\UserEvents
        - App\Entity\UsersDetails
